### ISSUE TITLE
lol

### ISSUE THREAD

**Issue by Crystallinqq** [jakepriddle/native-hwid-jna#1]
> Your program will be more secure as many people are unable to debug native programs.

More people know how to reverse x86 than jvm bytecode

**Comment by jakepriddle** [comment]
Many people in the crystalpvp client community are unable to code and reverse native programs, a small percentage are actually able to reverse native. This offers a good form of security to crackers who would normally just drop the jar in recaf.

**Comment by Crystallinqq** [comment]
k no one said this was for crystalpvp client... mr p..
